/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface ContactFormSubmission {
  'id' : bigint,
  'name' : string,
  'email' : string,
  'message' : string,
  'timestamp' : bigint,
}
export interface ContentBlock { 'title' : string, 'content' : string }
export interface GalleryItem {
  'id' : bigint,
  'title' : string,
  'description' : string,
  'imageUrl' : string,
  'dateAdded' : bigint,
}
export interface Notice {
  'id' : bigint,
  'title' : string,
  'body' : string,
  'date' : bigint,
}
export interface StaffMember {
  'id' : bigint,
  'name' : string,
  'biography' : string,
  'photoUrl' : string,
  'position' : string,
}
export interface UserProfile { 'name' : string, 'email' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addGalleryItem' : ActorMethod<[string, string, string], bigint>,
  'addNotice' : ActorMethod<[string, string, bigint], bigint>,
  'addStaffMember' : ActorMethod<[string, string, string, string], bigint>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'deleteContactSubmission' : ActorMethod<[bigint], undefined>,
  'deleteContentBlock' : ActorMethod<[string], undefined>,
  'deleteGalleryItem' : ActorMethod<[bigint], undefined>,
  'deleteNotice' : ActorMethod<[bigint], undefined>,
  'deleteStaffMember' : ActorMethod<[bigint], undefined>,
  'getAllContactSubmissions' : ActorMethod<[], Array<ContactFormSubmission>>,
  'getAllContentBlocks' : ActorMethod<[], Array<[string, ContentBlock]>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getContentBlock' : ActorMethod<[string], [] | [ContentBlock]>,
  'getGalleryItem' : ActorMethod<[bigint], [] | [GalleryItem]>,
  'getGalleryItems' : ActorMethod<[], Array<GalleryItem>>,
  'getNoticeById' : ActorMethod<[bigint], [] | [Notice]>,
  'getNotices' : ActorMethod<[], Array<Notice>>,
  'getStaffList' : ActorMethod<[], Array<StaffMember>>,
  'getStaffMember' : ActorMethod<[bigint], [] | [StaffMember]>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'submitContactForm' : ActorMethod<[string, string, string], undefined>,
  'updateContentBlock' : ActorMethod<[string, string, string], undefined>,
  'updateGalleryItem' : ActorMethod<
    [bigint, string, string, string],
    undefined
  >,
  'updateNotice' : ActorMethod<[bigint, string, string, bigint], undefined>,
  'updateStaffMember' : ActorMethod<
    [bigint, string, string, string, string],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];