/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ContactFormSubmission = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'email' : IDL.Text,
  'message' : IDL.Text,
  'timestamp' : IDL.Int,
});
export const ContentBlock = IDL.Record({
  'title' : IDL.Text,
  'content' : IDL.Text,
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Text,
});
export const GalleryItem = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'description' : IDL.Text,
  'imageUrl' : IDL.Text,
  'dateAdded' : IDL.Int,
});
export const Notice = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'body' : IDL.Text,
  'date' : IDL.Int,
});
export const StaffMember = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'biography' : IDL.Text,
  'photoUrl' : IDL.Text,
  'position' : IDL.Text,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addGalleryItem' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [IDL.Nat], []),
  'addNotice' : IDL.Func([IDL.Text, IDL.Text, IDL.Int], [IDL.Nat], []),
  'addStaffMember' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [IDL.Nat],
      [],
    ),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'deleteContactSubmission' : IDL.Func([IDL.Nat], [], []),
  'deleteContentBlock' : IDL.Func([IDL.Text], [], []),
  'deleteGalleryItem' : IDL.Func([IDL.Nat], [], []),
  'deleteNotice' : IDL.Func([IDL.Nat], [], []),
  'deleteStaffMember' : IDL.Func([IDL.Nat], [], []),
  'getAllContactSubmissions' : IDL.Func(
      [],
      [IDL.Vec(ContactFormSubmission)],
      ['query'],
    ),
  'getAllContentBlocks' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Text, ContentBlock))],
      ['query'],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getContentBlock' : IDL.Func([IDL.Text], [IDL.Opt(ContentBlock)], ['query']),
  'getGalleryItem' : IDL.Func([IDL.Nat], [IDL.Opt(GalleryItem)], ['query']),
  'getGalleryItems' : IDL.Func([], [IDL.Vec(GalleryItem)], ['query']),
  'getNoticeById' : IDL.Func([IDL.Nat], [IDL.Opt(Notice)], ['query']),
  'getNotices' : IDL.Func([], [IDL.Vec(Notice)], ['query']),
  'getStaffList' : IDL.Func([], [IDL.Vec(StaffMember)], ['query']),
  'getStaffMember' : IDL.Func([IDL.Nat], [IDL.Opt(StaffMember)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'submitContactForm' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  'updateContentBlock' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
  'updateGalleryItem' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text, IDL.Text],
      [],
      [],
    ),
  'updateNotice' : IDL.Func([IDL.Nat, IDL.Text, IDL.Text, IDL.Int], [], []),
  'updateStaffMember' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ContactFormSubmission = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'email' : IDL.Text,
    'message' : IDL.Text,
    'timestamp' : IDL.Int,
  });
  const ContentBlock = IDL.Record({ 'title' : IDL.Text, 'content' : IDL.Text });
  const UserProfile = IDL.Record({ 'name' : IDL.Text, 'email' : IDL.Text });
  const GalleryItem = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'description' : IDL.Text,
    'imageUrl' : IDL.Text,
    'dateAdded' : IDL.Int,
  });
  const Notice = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'body' : IDL.Text,
    'date' : IDL.Int,
  });
  const StaffMember = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'biography' : IDL.Text,
    'photoUrl' : IDL.Text,
    'position' : IDL.Text,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addGalleryItem' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [IDL.Nat], []),
    'addNotice' : IDL.Func([IDL.Text, IDL.Text, IDL.Int], [IDL.Nat], []),
    'addStaffMember' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'deleteContactSubmission' : IDL.Func([IDL.Nat], [], []),
    'deleteContentBlock' : IDL.Func([IDL.Text], [], []),
    'deleteGalleryItem' : IDL.Func([IDL.Nat], [], []),
    'deleteNotice' : IDL.Func([IDL.Nat], [], []),
    'deleteStaffMember' : IDL.Func([IDL.Nat], [], []),
    'getAllContactSubmissions' : IDL.Func(
        [],
        [IDL.Vec(ContactFormSubmission)],
        ['query'],
      ),
    'getAllContentBlocks' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Text, ContentBlock))],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getContentBlock' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(ContentBlock)],
        ['query'],
      ),
    'getGalleryItem' : IDL.Func([IDL.Nat], [IDL.Opt(GalleryItem)], ['query']),
    'getGalleryItems' : IDL.Func([], [IDL.Vec(GalleryItem)], ['query']),
    'getNoticeById' : IDL.Func([IDL.Nat], [IDL.Opt(Notice)], ['query']),
    'getNotices' : IDL.Func([], [IDL.Vec(Notice)], ['query']),
    'getStaffList' : IDL.Func([], [IDL.Vec(StaffMember)], ['query']),
    'getStaffMember' : IDL.Func([IDL.Nat], [IDL.Opt(StaffMember)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'submitContactForm' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
    'updateContentBlock' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [], []),
    'updateGalleryItem' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text, IDL.Text],
        [],
        [],
      ),
    'updateNotice' : IDL.Func([IDL.Nat, IDL.Text, IDL.Text, IDL.Int], [], []),
    'updateStaffMember' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };